# autogenerated, do not edit 
ccflags-y += -Wno-unused-function -Wno-unused-label -Wno-unused-variable 
obj-m += ./block_device_drivers/1-2-3-6-ram-disk/kernel/
obj-m += ./block_device_drivers/4-5-relay-disk/
